name       : lmdbxx
version    : 1.0.0
release    : 1
source     :
    - https://github.com/hoytech/lmdbxx/archive/refs/tags/1.0.0.tar.gz : 5e12eb3aefe9050068af7df2c663edabc977ef34c9e7ba7b9d2c43e0ad47d8df
license    : CC-PDDC
homepage   : https://github.com/hoytech/lmdbxx
component  : programming.library
summary    : C++ headers for LMDB
description: |
    C++ headers for LMDB
rundeps    :
    - lmdb-devel
install    : |
    make install DESTDIR="$installdir" PREFIX="/usr"
patterns   :
    - /*
